Update key vault and key vault key vault mgmt sdk for java from track1 to track2
Azure-Samples/key-vault-java-recovery pull request #2
Opened 2021-07-09 06:50 UTC by hongli750210

1. Update key vault and key vault key vault mgmt sdk for java from track1 to track2
2. Changed files:
    1). pom.xml
    2). src/main/java/BackupRestoreSample.java
    3) src/main/java/KeyVaultSampleBase.java
    4) src/main/java/SoftDeleteSample.java

@jongio for notification

2021-10-19 08:23 UTC, v-xuto commented
@scottaddie, @joshfree, @AlexGhiondea, @haolingdong-msft and @backwind1233  - Could you please review this PR?

2021-10-21 18:12 UTC, joshfree commented
@vcolin7 PTAL

2021-10-23 02:36 UTC, vcolin7 requested changes

2021-10-23 02:36 UTC, vcolin7 commented on pom.xml
> +            <version>2.6.0</version>
There's a new version of this library.
```suggestion
            <version>2.9.0</version>
```

2021-10-23 02:36 UTC, vcolin7 commented on pom.xml
> +            <version>1.18.0</version>
There's a new version of this library.
```suggestion
            <version>1.21.0</version>
```

2021-10-23 02:36 UTC, vcolin7 commented on pom.xml
> +            <version>1.3.1</version>
There's a new version of this library.
```suggestion
            <version>1.4.0</version>
```

2021-10-23 02:36 UTC, vcolin7 commented on pom.xml
> +            <version>4.3.0</version>
There's a new version of this library.
```suggestion
            <version>4.3.4</version>
```

2021-10-23 02:36 UTC, vcolin7 commented on pom.xml
> +            <version>4.2.0</version>
There's a new version of this library.
```suggestion
            <version>4.2.4</version>
```

2021-10-23 02:36 UTC, vcolin7 commented on pom.xml
> +            <version>4.3.0</version>
There's a new version of this library.
```suggestion
            <version>4.3.4</version>
```

2021-10-23 02:36 UTC, vcolin7 commented on pom.xml
>          </dependency>
This is duplicated.

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
> +        KeyAsyncClient keyAsyncClient = vault.keyClient();
I understand the `vault.keyClient()` method returns a `KeyAsyncClient`, so this kind of forces us to block if we want to make the code synchronous so it's easier to read for people not familiar with chaining reactive operations.

Have we considered directly creating a sync `KeyClient` using the same credentials and vault URL from the vault object resulting from creating a key vault?

```suggestion
        KeyClient keyClient = new KeyClientBuilder()
            .credential(createToken())
            .vaultUrl(vault.vaultUri())
            .buildClient();
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
> +        System.out.printf("Keys: %s.%n", Arrays.toString(keys.stream().collect(Collectors.toList()).toArray()));
I think it would be better to use our `KeyClient` for all key-related operations.

```suggestion
        PagedIterable<KeyProperties> keyProperties = keyClient.listPropertiesOfKeys();
        System.out.printf("Keys: %s.%n", Arrays.toString(keyProperties.stream().map(KeyProperties::getName).toArray()));
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
>          System.out.printf("Deleted keys %s.%n", Arrays.toString(deletedKeys.toArray()));
```suggestion
        PagedIterable<DeletedKey> deletedKeys = keyClient.listDeletedKeys();
        System.out.printf("Deleted keys: %s.%n",
            Arrays.toString(deletedKeys.stream().map(DeletedKey::getName).toArray()));
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
> +        System.out.printf("Keys: %s.%n", Arrays.toString(keys.stream().collect(Collectors.toList()).toArray()));
```suggestion
        keyProperties = keyClient.listPropertiesOfKeys();
        System.out.printf("Keys: %s.%n", Arrays.toString(keyProperties.stream().map(KeyProperties::getName)toArray()));
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
> +        SecretAsyncClient secretAsyncClient = vault.secretClient();
Similarly to above, I would suggest using a sync client.
```suggestion
        SecretClient secretClient = new SecretClientBuilder()
            .credential(createToken())
            .vaultUrl(vault.vaultUri())
            .buildClient();
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
>          System.out.printf("Secret: %s.%n", Arrays.toString(secrets.toArray()));
```suggestion
        PagedIterable<SecretProperties> secretProperties = secretClient.listPropertiesOfSecrets();
        System.out.printf("Secrets: %s.%n",
            Arrays.toString(secretProperties.stream().map(SecretProperties::getName).toArray()));
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
> +        System.out.printf("Deleted key %s.%n", deletedSecret);
```suggestion
        DeletedSecret deletedSecret = secretClient.beginDeleteSecret(secretToRecoverName).poll().getValue();
        pollOnSecretDeletion(secretClient, secretToRecoverName);
        System.out.printf("Deleted secret with name: %s%n", deletedSecret.getName());
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
> +        System.out.printf("Recovered key %s%n", keyVaultKey.toString());
```suggestion
        KeyVaultKey keyVaultKey = keyClient.beginRecoverDeletedKey(keyToRecoverName).poll().getValue();
        System.out.printf("Recovered key with name:%s%n", keyVaultKey.getName());
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
> +        System.out.printf("Create key %s.%n", key.getId().toString());
```suggestion
        KeyVaultKey key = keyClient.createRsaKey(new CreateRsaKeyOptions(keyToRecoverName).
                setKeyOperations(KeyOperation.UNWRAP_KEY, KeyOperation.WRAP_KEY,
                        KeyOperation.VERIFY, KeyOperation.ENCRYPT, KeyOperation.DECRYPT));
        System.out.printf("Created key with name: %s.%n", key.getName());
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
> +        System.out.printf("Create key %s.%n", key.getId());
```suggestion
        key = keyClient.createRsaKey(new CreateRsaKeyOptions(keyToPurgeName).
                setKeyOperations(KeyOperation.UNWRAP_KEY, KeyOperation.WRAP_KEY,
                        KeyOperation.VERIFY, KeyOperation.ENCRYPT, KeyOperation.DECRYPT));
        System.out.printf("Created key with name: %s.%n", key.getName());
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
>          System.out.printf("Deleted key %s.%n", deletedKey.toString());
```suggestion
        DeletedKey deletedKey = keyClient.beginDeleteKey(keyToRecoverName).poll().getValue();
        pollOnKeyDeletion(keyClient, keyToRecoverName);
        System.out.printf("Deleted key with name: %s.%n", deletedKey.getName());
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
>          System.out.printf("Deleted key %s.%n", deletedKey.toString());
```suggestion
        deletedKey = keyClient.beginDeleteKey(keyToPurgeName).poll().getValue();
        pollOnKeyDeletion(keyClient, keyToPurgeName);
        System.out.printf("Deleted key with name: %s.%n", deletedKey.getName());
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
>          System.out.printf("Purged key %s.%n,", keyToPurgeName);
```suggestion
        keyClient.purgeDeletedKey(keyToPurgeName);
        System.out.printf("Purged key with name: %s.%n,", keyToPurgeName);
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
> +        System.out.printf("Create secret %s.%n", secret.toString());
```suggestion
        KeyVaultSecret secret = secretClient.setSecret(secretToRecoverName, "secret to recover");
        System.out.printf("Create secret with name: %s.%n", secret.getName());

```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
>          System.out.printf("Create secret %s.%n", secret.toString());
```suggestion
        secret = secretClient.setSecret(secretToPurgeName, "secret to purge");
        System.out.printf("Create secret with name: %s.%n", secret.getName());

```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
> +        System.out.printf("Deleted key %s.%n", deletedSecret);
```suggestion
        deletedSecret = secretClient.beginDeleteSecret(secretToPurgeName).poll().getValue();
        pollOnSecretDeletion(secretClient, secretToPurgeName);
        System.out.printf("Deleted secret with name: %s.%n", deletedSecret.getName());
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
>          System.out.printf("Deleted secret %s.%n", Arrays.toString(deletedSecrets.toArray()));
```suggestion
        PagedIterable<DeletedSecret> secretProperties = secretClient.listDeletedSecrets();
        System.out.printf("Deleted secrets: %s.%n",
            Arrays.toString(deletedSecrets.stream().map(DeletedSecret::getName).toArray()));

```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
>          System.out.printf("Recovered secret %s%n", secret.toString());
```suggestion
        secret = secretClient.beginRecoverDeletedSecret(secretToRecoverName).poll().getValue();
        System.out.printf("Recovered secret with name: %s%n", secret.getName());
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
>          System.out.printf("Purged secret %s.%n,", secretToPurgeName);
```suggestion
        secretClient.purgeDeletedSecret(secretToPurgeName);
        System.out.printf("Purged secret with name: %s.%n,", secretToPurgeName);
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
>          System.out.printf("Secrets: %s.%n", Arrays.toString(secrets.toArray()));
```suggestion
        secretProperties = secretClient.listPropertiesOfSecrets();
        System.out.printf("Secrets: %s.%n",
            Arrays.toString(secretProperties.stream().map(SecretProperties::getName).toArray()));
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
>          System.out.printf("Create certificate %s.%n", certificate.toString());
```suggestion
        System.out.printf("Created certificate with name: %s.%n", certificate.getName());
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
>          System.out.printf("Create certificate %s.%n", certificatePurge.toString());
```suggestion
        System.out.printf("Created certificate with name: %s.%n", certificatePurge.getName());
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
>          System.out.printf("Certificate: %s.%n", Arrays.toString(certificates.toArray()));
```suggestion
        PagedIterable<CertificateProperties> certificates = certificateClient.listPropertiesOfCertificates();
        System.out.printf("Certificates: %s.%n",
            Arrays.toString(certificates.stream().map(CertificateProperties::getName).toArray()));
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
>          System.out.printf("Deleted certificate %s.%n", deletedCertificate.toString());
```suggestion
        System.out.printf("Deleted certificate with name: %s.%n", deletedCertificate.getName());

```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
>          System.out.printf("Deleted certificate %s.%n", deletedCertificate.toString());
```suggestion
        System.out.printf("Deleted certificate with name: %s.%n", deletedCertificate.getName());

```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
>          System.out.printf("Deleted certificate %s.%n", Arrays.toString(deletedCertificates.toArray()));
```suggestion
        PagedIterable<DeletedCertificate> deletedCertificates = certificateClient.listDeletedCertificates();
        System.out.printf("Deleted certificates: %s.%n",
            Arrays.toString(certifdeletedCertificates.stream().map(DeletedCertificate::getName).toArray()));
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
> +        System.out.printf("Recovered certificate %s.%n", recoveredCertificate.getPolicy().toString());
```suggestion
        System.out.printf("Recovered certificate with name: %s.%n", recoveredCertificate.getName());
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
>          System.out.printf("Purged certificate %s.%n,", certificateToPurgeName);
```suggestion
        System.out.printf("Purged certificate with name: %s.%n,", certificateToPurgeName);

```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
>          System.out.printf("Certificates: %s.%n", Arrays.toString(certificates.toArray()));
```suggestion
        certificates = certificateClient.listPropertiesOfCertificates();
        System.out.printf("Certificates: %s.%n",
            Arrays.toString(certificates.stream().map(CertificateProperties::getName).toArray()));
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
> +    protected static DeletedKey pollOnKeyDeletion(KeyAsyncClient keyAsyncClient, String keyName) throws Exception {
```suggestion
    protected static DeletedKey pollOnKeyDeletion(KeyClient keyClient, String keyName) throws Exception {

```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
> +            DeletedKey deleteKey = keyAsyncClient.getDeletedKeyWithResponse(keyName).block().getValue();
```suggestion
            DeletedKey deleteKey = keyClient.getDeletedKey("keyName");
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
> +    protected static DeletedSecret pollOnSecretDeletion(SecretAsyncClient secretAsyncClient, String secretName) throws Exception {
```suggestion
    protected static DeletedSecret pollOnSecretDeletion(SecretClient secretClient, String secretName) throws Exception {

```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
> +            DeletedSecret deletedSecret = secretAsyncClient.getDeletedSecret(secretName).block();
```suggestion
            DeletedSecret deletedSecret = secretClient.getDeletedSecret(secretName);

```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
> +import com.azure.security.keyvault.keys.KeyAsyncClient;
```suggestion
import com.azure.security.keyvault.keys.KeyClient;
import com.azure.security.keyvault.keys.KeyClientBuilder;
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/SoftDeleteSample.java
> +import com.azure.security.keyvault.secrets.SecretAsyncClient;
```suggestion
import com.azure.security.keyvault.secrets.SecretClient;
import com.azure.security.keyvault.secrets.SecretClientBuilder;
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/BackupRestoreSample.java
> +        SecretAsyncClient secretAsyncClient = firstVault.secretClient();
```suggestion
        SecretClient secretClient = new SecretClientBuilder()
            .vaultUrl(firstVault.vaultUri())
            .credential(createToken())
            .buildClient();
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/BackupRestoreSample.java
> +        System.out.printf("Created secret %s%n", secret.getId());
```suggestion
        KeyVaultSecret secret = secretClient.setSecret(secretName, secretValue);
        System.out.printf("Created secret with name: %s%n", secret.getName());

```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/BackupRestoreSample.java
> +        System.out.printf("Backed up secret %s%n", new String(backup, StandardCharsets.UTF_8));
```suggestion
        byte[] backup = secretClient.backupSecret(secretName);
        System.out.printf("Backed up secret: %s%n", new String(backup, StandardCharsets.UTF_8));

```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/BackupRestoreSample.java
>          System.out.printf("Vault %s secrets: %s%n", firstVault.vaultUri(), Arrays.toString(secrets.toArray()));
```suggestion
        PagedIterable<SecretProperties> secretProperties = secretClient.listPropertiesOfSecrets();
        System.out.printf("Vault %s secrets: %s%n", firstVault.vaultUri(),
            Arrays.toString(secretProperties.map(SecretProperties::getName).toArray()));

```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/BackupRestoreSample.java
>          System.out.printf("Restored secret %s%n", restored.toString());
```suggestion
        KeyVaultSecret restoredSecret = secondSecretClient.restoreSecretBackup(backup);
        System.out.printf("Restored secret with name: %s%n", restoredSecret.getName());

```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/BackupRestoreSample.java
>          System.out.printf("Vault %s secrets: %s%n", secondVault.vaultUri(), Arrays.toString(newVaultSecrets.toArray()));
```suggestion
        PagedIterable<SecretProperties> newVaultSecretProperties = secondSecretClient.listPropertiesOfSecrets();
        System.out.printf("Vault %s secrets: %s%n", secondVault.vaultUri(),
            Arrays.toString(newVaultSecretProperties.map(SecretProperties::getName).toArray()));
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/BackupRestoreSample.java
>          Vault secondVault = createKeyVault(getRandomName("vault"), RESOURCE_GROUP);
```suggestion
        Vault secondVault = createKeyVault(getRandomName("vault"), RESOURCE_GROUP);
        SecretClient secondSecretClient = new SecretClientBuilder()
            .vaultUrl(secondVault.vaultUri())
            .credential(createToken())
            .buildClient();
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/BackupRestoreSample.java
> +        KeyAsyncClient keyAsyncClient = firstVault.keyClient();
```suggestion
        KeyClient keyClient = new KeyClientBuilder()
            .vaultUrl(firstVault.vaultUri())
            .credential(createToken())
            .buildClient();
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/BackupRestoreSample.java
>          System.out.printf("Created key %s%n", key.toString());
```suggestion
        KeyVaultKey key = keyClient.createRsaKey(new CreateRsaKeyOptions(keyName)
                .setKeyOperations(KeyOperation.UNWRAP_KEY, KeyOperation.WRAP_KEY, KeyOperation.DECRYPT,
                        KeyOperation.ENCRYPT, KeyOperation.SIGN, KeyOperation.VERIFY));
        System.out.printf("Created key with name: %s%n", key.getName());

```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/BackupRestoreSample.java
> +        System.out.printf("Vault %s keys: %s%n", firstVault.vaultUri(), Arrays.toString(keys.stream().collect(Collectors.toList()).toArray()));
```suggestion
        PagedIterable<KeyProperties> keyProperties = keyClient.listPropertiesOfKeys();
        System.out.printf("Vault %s keys: %s%n", firstVault.vaultUri(),
            Arrays.toString(keyProperties.stream().map(KeyProperties::getName).toArray()));

```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/BackupRestoreSample.java
> +        System.out.printf("Backed up key %s%n", new String(backup, StandardCharsets.UTF_8));
```suggestion
        byte[] backup = keyClient.backupKey(keyName);
        System.out.printf("Backed up key: %s%n", new String(backup, StandardCharsets.UTF_8));

```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/BackupRestoreSample.java
>          System.out.printf("Restored key %s%n", restored.toString());
```suggestion
        KeyVaultKey restoredKey = secondKeyClient.restoreKeyBackup(backup);
        System.out.printf("Restored key with name: %s%n", restoredKey.getName());

```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/BackupRestoreSample.java
>          Vault secondVault = createKeyVault(getRandomName("vault"), RESOURCE_GROUP);
```suggestion
        Vault secondVault = createKeyVault(getRandomName("vault"), RESOURCE_GROUP);
        KeyClient secondKeyClient = new KeyClientBuilder()
            .vaultUrl(secondVault.vaultUri())
            .credential(createToken())
            .buildClient();
```

2021-10-23 02:36 UTC, vcolin7 commented on src/main/java/BackupRestoreSample.java
> +        System.out.printf("Vault %s keys: %s%n", secondVault.vaultUri(), Arrays.toString(newVaultKeys.stream().collect(Collectors.toList()).toArray()));
```suggestion
        PagedIterable<KeyProperties> newVaultKeyProperties = secondVault.listPropertiesOfKeys();
        System.out.printf("Vault %s keys: %s%n", secondVault.vaultUri(),
            Arrays.toString(newVaultKeys.stream().map(KeyProperties::getName).toArray()));

```

2021-10-25 06:59 UTC, v-hongli1 commented on src/main/java/BackupRestoreSample.java
> +        System.out.printf("Vault %s keys: %s%n", secondVault.vaultUri(), Arrays.toString(newVaultKeys.stream().collect(Collectors.toList()).toArray()));
Fixed in the new version

2021-10-25 08:57 UTC, v-xuto commented
@vcolin7 We have updated code by your comments, please re-review this PR.

2021-10-26 10:34 UTC, vcolin7 approved these changes

2021-10-29 16:47 UTC, merged